quarkus.application.name=jfood-recomendacoes
quarkus.http.port=8084

quarkus.neo4j.uri=bolt://localhost:7687
quarkus.neo4j.authentication.username=neo4j
quarkus.neo4j.authentication.password=neo4jpassword

quarkus.neo4j.devservices.enabled=false
