quarkus.application.name=jfood-catalogo
quarkus.http.port=8082

quarkus.mongodb.connection-string=mongodb://admin:adminpassword@localhost:27017/?authSource=admin
jnosql.document.database=jfood_catalogo

quarkus.mongodb.devservices.enabled=false
